# Generated by Django 5.0.6 on 2024-05-12 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'active'), (3, 'rejected'), (4, 'paid')], default=1)),
                ('contract_version', models.TextField(blank=True, max_length=30, null=True)),
                ('maximum_payment_date', models.DateTimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now=True, null=True)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loan', to='customer.customer')),
            ],
        ),
    ]
